OnlineProjectTracking/Controllers/ManagerCommentsController.cs
using System.Linq;
using System.Web.Mvc;
using OnlineProjectTracking.DAL;
using System.Collections.Generic;
namespace OnlineProjectTracking.Controllers
{
    public class ManagerCommentsController : Controller
    {

       
        [HttpGet]
        public ActionResult AddComment(int id)
        {
            ViewBag.TaskID = id;
            return View();
        }

        [HttpPost]
        public ActionResult AddComment(ManagerComment managerComment)
        {
            ViewBag.TaskID = managerComment.ProjectTaskID;
            try
            {
                if (!ModelState.IsValid)
                    return View();
                else
                {
                    OPTDBContext dbEntities = new OPTDBContext();
                    dbEntities.ManagerComments.Add(managerComment);
                    dbEntities.SaveChanges();
                    TempData["newcomment_success"] = "added";
                    return View();
                }
            }
            catch (System.Exception)
            {
                TempData["newcomment_error"] = "error";
            }
            return View();
        }
    }
}

OnlineProjectTracking/Controllers/ProjectTasksController.cs
using OnlineProjectTracking.DAL;
using OnlineProjectTracking.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace OnlineProjectTracking.Controllers
{
    [CustomActionFilter]
    public class ProjectTasksController : Controller
    {
        // GET: ProjectTasks
        public ActionResult Index()
        {
            OPTDBContext context = new OPTDBContext();
            List<ProjectTask> projectTasks;
            if (!Session["role"].ToString().Equals("Developer") && !Session["role"].ToString().Equals("Designer"))
            {
                projectTasks = context.ProjectTasks.ToList();
            }
            else
            {
                int useID = int.Parse(Session["user_id"].ToString().Trim());
                projectTasks = context.ProjectTasks.Where(task => task.AssignedTo == useID).ToList();
            }
            return View(projectTasks);
        }


        [HttpGet]
        public ActionResult AddNewTask()
        {
            ViewBag.Employees = GetEmployeeList();
            ViewBag.UserStories = GetUserStoriesList();
            ViewBag.TaskTypes = GetTaskTypeList();
            return View();
        }

        [HttpPost]
        public ActionResult AddNewTask(ProjectTask projectTask)
        {
            ViewBag.Employees = GetEmployeeList();
            ViewBag.UserStories = GetUserStoriesList();
            ViewBag.TaskTypes = GetTaskTypeList();
            try
            {
                if (!ModelState.IsValid)
                    return View();

                OPTDBContext dbEntities = new OPTDBContext();
                dbEntities.ProjectTasks.Add(projectTask);
                dbEntities.SaveChanges();
                TempData["newtask_success"] = "added";
            }
            catch (System.Exception)
            {
                TempData["newtask_error"] = "error";
            }
            return View();
        }


        private List<SelectListItem> GetEmployeeList()
        {
            List<SelectListItem> employees = new List<SelectListItem>() { new SelectListItem { Text = "Please select", Value = "", Disabled = true, Selected = true } };
            OPTDBContext dbEntities = new OPTDBContext();
            List<Employee> dbemployees = dbEntities.Employees.Where(emp => emp.Designation != "Project Manager" && emp.Designation != "Business Analyst" && emp.Designation != "Admin").ToList();
            foreach (Employee employee in dbemployees)
            {
                employees.Add(new SelectListItem()
                {
                    Text = employee.EmployeeName,
                    Value = employee.EmployeeID.ToString()
                });
            }
            return employees;
        }


        private List<SelectListItem> GetUserStoriesList()
        {
            List<SelectListItem> userstories = new List<SelectListItem>() { new SelectListItem { Text = "Please select", Value = "", Disabled = true, Selected = true } };
            OPTDBContext dbEntities = new OPTDBContext();
            List<UserStory> dbuserstories = dbEntities.UserStories.ToList();
            foreach (UserStory userStory in dbuserstories)
            {
                userstories.Add(new SelectListItem()
                {
                    Text = userStory.Story,
                    Value = userStory.UserStoryID.ToString()
                });
            }
            return userstories;
        }

        private List<SelectListItem> GetTaskTypeList()
        {
            List<SelectListItem> taskTypeList = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Please select", Value = "", Disabled = true, Selected = true },
                new SelectListItem {Text = "Technical Documentation", Value = "Technical Documentation" },
                new SelectListItem {Text = "Timeline", Value = "Timeline" },
                new SelectListItem {Text = "Code", Value = "Code" },
                new SelectListItem {Text = "User Documentation", Value = "User Documentation" },
                new SelectListItem {Text = "Miscellaneous", Value = "Miscellaneous" },
            };
            return taskTypeList;
        }


        [HttpPost]
        public JsonResult MarkCompleted(int task_id, int task_status)
        {
            try
            {
                OPTDBContext context = new OPTDBContext();
                ProjectTask projectTask = context.ProjectTasks.FirstOrDefault(pt => pt.ProjectTaskID == task_id);
                if (projectTask != null)
                {
                    projectTask.TaskStatus = task_status;
                    context.SaveChanges();
                    return Json(new { code = 200 });
                }
                return Json(new { code = 500 });
            }
            catch (System.Exception)
            {
                return Json(new { code = 200 });
            }
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            try
            {
                OPTDBContext context = new OPTDBContext();
                ProjectTask projectTask = context.ProjectTasks.FirstOrDefault(pt => pt.ProjectTaskID == id);
                return View(projectTask);
            }
            catch (System.Exception)
            {
                return View(new ProjectTask());
            }
        }

        [HttpGet]
        public ActionResult UploadTask(int id)
        {
            try
            {
                OPTDBContext context = new OPTDBContext();
                ProjectTask projectTask = context.ProjectTasks.FirstOrDefault(pt => pt.ProjectTaskID == id);
                return View(projectTask);
            }
            catch (System.Exception)
            {
                return View(new ProjectTask());
            }
        }

        [HttpPost]
        public ActionResult UploadTask(ProjectTask projectTask)
        {
            try
            {
                OPTDBContext context = new OPTDBContext();
                ProjectTask projectTaskDB = context.ProjectTasks.FirstOrDefault(pt => pt.ProjectTaskID == projectTask.ProjectTaskID);
                projectTaskDB.TaskCompletionDesciption = string.IsNullOrEmpty(projectTask.TaskCompletionDesciption) ? "" : projectTask.TaskCompletionDesciption;
                HttpPostedFileBase file = Request.Files["file"];
                if (file != null && file.ContentLength > 0)
                {
                    string FileName = DateTime.Now.ToString("yyyyMMddHHmmssfff") + "-" + file.FileName;
                    string path = Server.MapPath("~/Content/Uploads/" + FileName);
                    file.SaveAs(path);
                    projectTaskDB.TaskData = FileName;
                }
                context.SaveChanges();
                TempData["data_upload_ok"] = "Ok";
                return View(projectTask);
            }
            catch (System.Exception ex)
            {
                TempData["data_upload_error"] = ex.ToString();
                return View(new ProjectTask());
            }
        }

        public FileResult DownloadTaskData(int id)
        {
            OPTDBContext context = new OPTDBContext();
            ProjectTask projectTaskDB = context.ProjectTasks.FirstOrDefault(pt => pt.ProjectTaskID == id);
            string fileName = projectTaskDB.TaskData;
            string path = Server.MapPath("~/Content/Uploads/" + fileName);
            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
            //return File(path, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

OnlineProjectTracking/Views/ProjectTasks/AddNewTask.cshtml
@model OnlineProjectTracking.DAL.ProjectTask
@{
    ViewBag.Title = "Add New Task";
}
<div class="row" style="margin-top:30px;">
    <div class="col-md-8 col-md-offset-2">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <h4>Add New Task</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <label class="control-label col-md-2">User Story</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.UserStoryID, (IEnumerable<SelectListItem>)ViewBag.UserStories, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.UserStoryID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Assigned To</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.AssignedTo, (IEnumerable<SelectListItem>)ViewBag.Employees, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.AssignedTo, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Task Name</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TaskName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        @Html.ValidationMessageFor(model => model.TaskName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Task Type</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.TaskType, (IEnumerable<SelectListItem>)ViewBag.TaskTypes, new { @class = "form-control", @required = "required" })
                        @Html.ValidationMessageFor(model => model.TaskType, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Start Date</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TaskStartDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TaskStartDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">End Date</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TaskEndDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TaskEndDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 col-md-offset-4">
                        <button type="submit" class="btn btn-primary col-md-12">Add New Task</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.datetimepicker.full.min.js"></script>
    <script>
        jQuery('#TaskStartDate').datetimepicker(
            {
                value: new Date(),
                format: 'Y-m-d H:i:s',
            });
        jQuery('#TaskEndDate').datetimepicker(
            {
                value: new Date(),
                format: 'Y-m-d H:i:s',
            });
    </script>
    @if (TempData["newtask_success"] != null)
    {
        <script>
            swal("Success", "New task added successfully", "success");
        </script>
    }
    @if (TempData["newtask_error"] != null)
    {
        <script>
            swal("Server Error", "Unknown server error while adding new task", "error");
        </script>
    }
}

OnlineProjectTracking/Views/ProjectTasks/Details.cshtml
@model OnlineProjectTracking.DAL.ProjectTask
@{
    ViewBag.Title = "Details";
}
<div class="row" style="margin-top:30px;">
    <h4 style="float:left;margin-left:20px;">Task Details</h4>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <table style="width:100%;">
            <tbody>
                <tr class="task-details-tr">
                    <th> Project Name </th>
                    <td> @Html.DisplayFor(model => model.UserStory.Project.ProjectName) </td>
                </tr>
                <tr class="task-details-tr">
                    <th> User Story </th>
                    <td> @Html.DisplayFor(model => model.UserStory.Story) </td>
                </tr>
                <tr class="task-details-tr">
                    <th>Assigned To</th>
                    <td> @Html.DisplayFor(model => model.Employee.EmployeeName) </td>
                </tr>
                <tr class="task-details-tr">
                    <th>Start Date</th>
                    <td>   @Html.DisplayFor(model => model.TaskStartDate) </td>
                </tr>
                <tr class="task-details-tr">
                    <th>End Date</th>
                    <td> @Html.DisplayFor(model => model.TaskEndDate) </td>
                </tr>

                <tr class="task-details-tr">
                    <th>Task Name</th>
                    <td> @Html.DisplayFor(model => model.TaskName) </td>
                </tr>
                <tr class="task-details-tr">
                    <th>Task Type</th>
                    <td> @Html.DisplayFor(model => model.TaskType)</td>
                </tr>
                <tr class="task-details-tr">
                    <th>Task Data</th>
                    <td>
                        @if (string.IsNullOrEmpty(Model.TaskData))
                        {
                            <span>NA</span>
                        }
                        else
                        {
                            @Html.ActionLink("Download Data", "DownloadTaskData", "ProjectTasks", new { id = Model.ProjectTaskID }, new { })
                        }
                    </td>
                </tr>
                <tr class="task-details-tr">
                    <th>Employee Response</th>
                    <td>
                        @if (string.IsNullOrEmpty(Model.TaskCompletionDesciption))
                        {
                            <span>NA</span>
                        }
                        else
                        {
                            @Html.DisplayFor(model => model.TaskCompletionDesciption)
                        }
                    </td>
                </tr>
                <tr class="task-details-tr">
                    <th> Manager Comments </th>
                    <td> @Html.DisplayFor(model => model.ManagerComments.FirstOrDefault(m => m.ProjectTaskID == Model.ProjectTaskID).Comments) </td>
                </tr>
                <tr class="task-details-tr">
                    <th>Task Status</th>
                    <td>
                        @if (Model.TaskStatus == 0)
                        {
                            <span class="task-status task-pending">Pending</span>
                        }
                        else
                        {
                            <span class="task-status task-completed">Completed</span>
                        }
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<br />
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

OnlineProjectTracking/Views/ProjectTasks/Index.cshtml
@model IEnumerable<OnlineProjectTracking.DAL.ProjectTask>
@{
    ViewBag.Title = "Project Tasks";
}
<div class="row" style="margin-top:30px;">
    <h4 style="float:left;margin-left:20px;">View All Tasks</h4>
    @if (!Session["role"].ToString().Equals("Developer") && !Session["role"].ToString().Equals("Designer"))
    {
        <a href="@Url.Action("AddNewTask")" class="btn btn-primary" style="float:right;margin-right:20px;">Add New Project Task</a>
    }
</div>
<hr />
<table class="table table-striped table-hover">
    <tr class="info">
        <th>Task Name</th>
        <th>Assigned To</th>
        <th>Task Start</th>
        <th>Task End</th>
        <th>Task Type</th>
        <th>Task Status</th>
        <th>Mark Completed</th>
        <th>Actions</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr class="success">
            <td>
                @Html.DisplayFor(modelItem => item.TaskName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.EmployeeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TaskStartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TaskEndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TaskType)
            </td>
            <td>
                @if (item.TaskStatus == 0)
                {
                    <span class="task-status task-pending" id="@item.ProjectTaskID">Pending</span>
                }
                else
                {
                    <span class="task-status task-completed" id="@item.ProjectTaskID">Completed</span>
                }
            </td>
            <td style="text-align:center">
                @if (item.TaskStatus == 0)
                {
                    @Html.CheckBox("task_status", false, new { @id = item.ProjectTaskID, @class = "regular-checkbox", @onclick = "SetTaskStatus(this)" })
                }
                else
                {
                    @Html.CheckBox("task_status", true, new { @id = item.ProjectTaskID, @class = "regular-checkbox", @onclick = "SetTaskStatus(this)" })
                }
            </td>
            <td>
                @if (!Session["role"].ToString().Equals("Developer") && !Session["role"].ToString().Equals("Designer"))
                {
                    @Html.ActionLink("Add Comment", "AddComment", "ManagerComments", new { id = item.ProjectTaskID }, new { })

                }
                else
                {
                    @Html.ActionLink("Upload Task", "UploadTask", "ProjectTasks", new { id = item.ProjectTaskID }, new { })
                }
                <span> | </span>
                @Html.ActionLink("Details", "Details", "ProjectTasks", new { id = item.ProjectTaskID }, new { })
            </td>
        </tr>
    }
</table>
<script>
    function SetTaskStatus(data) {
        var selected_task_id = data.id;
        console.log(selected_task_id);
        var status = $(data).is(':checked') == true ? 1 : 0;
        $.ajax({
            url: '/ProjectTasks/MarkCompleted',
            type: 'POST',
            data: { task_id: selected_task_id, task_status: status },
            success: function (data) {
                if (data.code == 200) {
                    if (status == 0) {
                        $('#' + selected_task_id).removeClass('task-completed');
                        $('#' + selected_task_id).addClass('task-pending');
                        $('#' + selected_task_id).text('Pending');
                    }
                    else {
                        $('#' + selected_task_id).removeClass('task-pending');
                        $('#' + selected_task_id).addClass('task-completed');
                        $('#' + selected_task_id).text('Completed');
                    }
                }
                else {
                    alert('unknown server error');
                }
            },
            error: function (x1, x2, x3) {
                console.log(x1);
                console.log(x2);
                console.log(x3);
            }
        });
    }
</script>

OnlineProjectTracking/Views/ProjectTasks/UploadTask.cshtml
@model OnlineProjectTracking.DAL.ProjectTask

@{
    ViewBag.Title = "UploadTask";
}
<div class="row" style="margin-top:30px;">
    <div class="col-md-8 col-md-offset-2">
        @using (Html.BeginForm("UploadTask", "ProjectTasks", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <h4>Upload Task</h4>
                <hr />
                @Html.HiddenFor(model => model.ProjectTaskID)
                <div class="form-group">
                    @Html.LabelFor(model => model.TaskName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TaskName, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.TaskName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Task Data</label>
                    <div class="col-md-10">
                        <input type="file" name="file" id="file" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Task Completion Desciption</label>
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.TaskCompletionDesciption, 5, 20, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TaskCompletionDesciption, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 col-md-offset-4">
                        <button type="submit" class="btn btn-primary col-md-12">Upload Task</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @if (TempData["data_upload_ok"] != null)
    {
        <script>
            swal("Success", "Task data uploaded successfully", "success");
        </script>
    }
    @if (TempData["data_upload_error"] != null)
    {
        <script>
            console.log('@TempData["data_upload_error"].ToString()');
            swal("Server Error", "Unknown server error while uploading task data", "error");
        </script>
    }
}